server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:calcDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
logging:
  level:
    org.hibernate.orm.connections.pooling: ERROR